In [1]:
import numpy as np


In [3]:
#Ans1 -- Option C
my_array = np.array([[[[1,3,4]]]])
np.array(my_array, ndmin=5)

array([[[[[1, 3, 4]]]]])

In [4]:
#Ans 2 
#definition of Array1 and Array2 gives name error as the syntax is np.array([[1,2,3],[4,5,6]])
#even if that is resolved the dot product would not be performed and value error will be given as 
#the dimensions of bothe the array is different


Array1 =np.array([[1, 2, 3], [4, 5, 6]]) 
Array2 =np.array([[2, 3],[3, 2]])
np.dot(Array1,Array2)

ValueError: ignored

In [5]:
#ANS 3 -- Option C
Array3=np.array([10,3,1,203,404,204,20,302,30,402,192])
Array3[::-1]

array([192, 402,  30, 302,  20, 204, 404, 203,   1,   3,  10])

In [7]:
#ANS 4 -- Option B
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.dot(a, b)

array([[4, 1],
       [2, 2]])

In [10]:
#ANS 5 -- OPTION A
a = np.arange(3*4*5*6).reshape((3,4,5,6))
b = np.arange(3*4*5*6)[::-1].reshape((5,4,6,3))
np.dot(a, b)[2,3,2,1,2,2]

499128

In [12]:
#ANS 6 -- Option A

a = np.array([3, 7, 32], dtype = complex)
print(a)

[ 3.+0.j  7.+0.j 32.+0.j]


In [15]:
#ANS7 -- Option C
np.random.seed(100)
ar1 = np.random.uniform(1,50,20)
ar2 = np.clip(ar1, a_min=10, a_max=30)
ar3 = np.where(ar1 < 10, 10, np.where(ar1 > 30, 30, ar1))
print(ar1)
print(ar2)
print(ar3)

[27.62684215 14.64009987 21.80136195 42.39403048  1.23122395  6.95688692
 33.86670515 41.466785    7.69862289 29.17957314 44.67477576 11.25090398
 10.08108276  6.31046763 11.76517714 48.95256545 40.77247431  9.42510962
 40.99501269 14.42961361]
[27.62684215 14.64009987 21.80136195 30.         10.         10.
 30.         30.         10.         29.17957314 30.         11.25090398
 10.08108276 10.         11.76517714 30.         30.         10.
 30.         14.42961361]
[27.62684215 14.64009987 21.80136195 30.         10.         10.
 30.         30.         10.         29.17957314 30.         11.25090398
 10.08108276 10.         11.76517714 30.         30.         10.
 30.         14.42961361]


In [14]:
#ANS 8 OPTION --D
array = np.array([10,3,1,203,404,204,20,302,30,402,192])
array2 = [1,2,3,4]
np.insert(array,4,array2)

array([ 10,   3,   1, 203,   1,   2,   3,   4, 404, 204,  20, 302,  30,
       402, 192])

In [17]:
#ANS 9 OPTION -- C
np.full((3,3), 'k')

array([['k', 'k', 'k'],
       ['k', 'k', 'k'],
       ['k', 'k', 'k']], dtype='<U1')

In [19]:
#ANS 10 OPTION -- B
def bub_sort(array):
    for i in range(0, len(array)):
        for j in range(0, len(array) - i - 1):
            if array[j] < array[j + 1]:
                temp = array[j]
                array[j] = array[j + 1]
                array[j+1] = temp
    return array
array = np.array([20,14,25,16,45,60,12,9])
bub_sort(array)

array([60, 45, 25, 20, 16, 14, 12,  9])

In [21]:
#ANS 11 OPTION -- D
arr = np.full((2,5),40)
print(arr)
arr.reshape(5,2)

[[40 40 40 40 40]
 [40 40 40 40 40]]


array([[40, 40],
       [40, 40],
       [40, 40],
       [40, 40],
       [40, 40]])

In [23]:
#ANS 12 OPTION -- A
Sample = np.array([[1,2],[3,4],[5,6],[7,8]])
Sample.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
#ANS 13 OPTION -- A
ARRAY6 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
ARRAY6[0:3,1]

array([2, 5, 8])

In [27]:
#ANS 14 OPTION -- D
ARRAY7 = np.arange(19,0,-2)
print(ARRAY7)
ARRAY8 = np.array([1,2,3,4,5,6,7,8,9,10])
print(ARRAY8)
np.hstack((ARRAY7,ARRAY8))

[19 17 15 13 11  9  7  5  3  1]
[ 1  2  3  4  5  6  7  8  9 10]


array([19, 17, 15, 13, 11,  9,  7,  5,  3,  1,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10])

In [28]:
#ANS 15 OPTION -- A
array9 = np.array([[1,2],[3,4]])
array10 = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
np.vstack((array9,array10))

array([[ 1,  2],
       [ 3,  4],
       [ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [29]:
#ANS 16 OPTION -- A
array11 = np.array([[1,2],[3,4]])
array12 = np.array([[5,6],[7,8]])
np.hstack((array11,array12))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [50]:
#ANS 17 
'''
The cross product of vector of length 13 is not possible since the required dimension is 3,
hence we can convert the vector to 5,3 dimension array and then get the cross product of the vectors and 
again convert the result into a 1 dimension vector
'''
A = np.array([1,3,5,7,9,11,13,15,17,19,21,23,25])
B = np.array([0,2,4,6,8,10,12,14,16,18,20, 22,24])

length=np.size(A)

def ArrayReshape(array):
    if len(array) % 3 == 0:
        pass
    elif len(array) % 3 == 1:
        bef_final_array=np.append(array,0)
        final_array=np.append(bef_final_array,0)
    elif len(array) % 3 == 2:
        final_array=np.append(array,0)
    
    return final_array

    
fin_A=ArrayReshape(A).reshape(5,3)
fin_B=ArrayReshape(B).reshape(5,3)
D=np.cross(fin_A,fin_B)
print(D)
print('Cross Product is ',D[0,0],'i +',D[0,1],'j +',D[0,2],'k')

[[ 2 -4  2]
 [ 2 -4  2]
 [ 2 -4  2]
 [ 2 -4  2]
 [ 0  0  0]]
Cross Product is  2 i + -4 j + 2 k


**#Ans 18** 


In [51]:
np.corrcoef(A)

1.0

In [52]:
np.corrcoef(B)

1.0

In [53]:
np.corrcoef(A,B)

array([[1., 1.],
       [1., 1.]])

**#ANS 19**

In [148]:

sample = {1: [1,2],2: [[1],[2]],3: [[1,2], [3,4], [4,5]],4: [1],5: [1,2,3,4,5]} 
values=list(sample.values())
np.array(values,dtype=object).reshape(5,1)




array([[list([1, 2])],
       [list([[1], [2]])],
       [list([[1, 2], [3, 4], [4, 5]])],
       [list([1])],
       [list([1, 2, 3, 4, 5])]], dtype=object)

In [147]:
'''Create a 2-dimensional array with 3 rows and 3 columns containing random numbers from
1 to 9. Find the difference between the maximum element across the columns and the
minimum element across the rows.'''



ArrayRand=np.random.randint(10,size=(3,3))
print(ArrayRand)
print('DIFFERENCE : ',np.subtract(np.max(ArrayRand,axis=1),np.min(ArrayRand,axis=0)))



[[3 9 2]
 [3 8 7]
 [1 5 9]]
DIFFERENCE :  [8 3 7]
